# Generated by Chocoleotey. https://github.com/leobastiani/chocoleotey

$ErrorActionPreference = 'Stop';
$toolsDir = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"

Install-BinFile -Name 'fone' -Path (Join-Path (Join-Path $toolsDir 'bin') 'fone.bat')
Install-BinFile -Name 'tv' -Path (Join-Path (Join-Path $toolsDir 'bin') 'tv.bat')
